### ISSUE TITLE
Move initial setActivationStatus to app code

### ISSUE THREAD

**Issue by ashercoren** [getvim/vim-canvas-demo-app#1]
The initial setActivationStatus is currently in the AppWrapper, which make it a little hidden from the app code.

https://github.com/getvim/vim-canvas-demo-app/blob/e8281aaf538bc7b95eb945c8ecf84adaff396380/vim-canvas-demo-app-react/src/AppWrapper.tsx#L20

I suggest moving it to somewhere in the App code

**Comment by vim-daniel** [comment]
done
